name: reward_hub_customer
description: "BizAtom"
publish_to: 'none'
version: 2.0.5+12

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get_storage:
  page_transition:
  fluttertoast:
  flutter_easyloading:
  http:
  country_code_picker:
  animated_notch_bottom_bar:
  popup_banner:
  carousel_slider:
  cached_network_image: ^3.4.0
  url_launcher: ^6.0.20
  flutter_phone_direct_caller: ^2.1.0
  image_picker: any
  device_info_plus: any
  geolocator:
  pinput:
  dio:
  mime:
  http_parser:
  qr_flutter:
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  flip_card: ^0.7.0
  webview_flutter: ^4.4.3
  flutter_screenutil: ^5.9.0
  package_info_plus: ^8.2.1
  provider: ^6.1.1
  image_cropper: ^9.1.0
  full_screen_image: ^2.0.0
  curved_navigation_bar: ^1.0.3
  shimmer: ^3.0.0
  super_banners: ^0.0.1
  # flutter_typeahead: ^4.0.0
  uuid: ^4.5.1
  slide_to_act: ^2.0.2
  # flutter_local_notifications: ^17.2.2
  app_settings: ^5.1.1
  build_runner: ^2.4.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/